-- MySQL Script generated by MySQL Workbench
-- Fri Apr 17 18:48:19 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Contato` VARCHAR(45) NULL,
  `cpf_cnpj` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe` (
  `idEquipe` INT NOT NULL,
  `Nome_Equipe` VARCHAR(45) NULL,
  PRIMARY KEY (`idEquipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veículo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veículo` (
  `idVeículo` INT NOT NULL,
  `Placa` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  `Marca` VARCHAR(45) NULL,
  `Ano` INT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Equipe_idEquipe` INT NOT NULL,
  PRIMARY KEY (`idVeículo`, `Cliente_idCliente`, `Equipe_idEquipe`),
  UNIQUE INDEX `Placa_UNIQUE` (`Placa` ASC) VISIBLE,
  INDEX `fk_Veículo_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Veículo_Equipe1_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Veículo_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veículo_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecânicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecânicos` (
  `idMecânicos` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Código` VARCHAR(45) NULL,
  `Especialidade` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Equipe_idEquipe` INT NOT NULL,
  PRIMARY KEY (`idMecânicos`, `Equipe_idEquipe`),
  INDEX `fk_Mecânicos_Equipe1_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Mecânicos_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço` (
  `idOrdem de Serviço` INT NOT NULL,
  `Número` INT NULL,
  `Data de Emissão` DATE NULL,
  `Valor` DECIMAL(10,2) NULL,
  `Status` VARCHAR(45) NULL,
  `Conclusão` DATE NULL,
  `tipo-de-Serviço` VARCHAR(45) NULL,
  `Veículo_idVeículo` INT NOT NULL,
  `Equipe_idEquipe` INT NOT NULL,
  PRIMARY KEY (`idOrdem de Serviço`, `Veículo_idVeículo`, `Equipe_idEquipe`),
  UNIQUE INDEX `Número_UNIQUE` (`Número` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_Veículo1_idx` (`Veículo_idVeículo` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_Equipe1_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_Veículo1`
    FOREIGN KEY (`Veículo_idVeículo`)
    REFERENCES `mydb`.`Veículo` (`idVeículo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Serviço` (
  `idServiço` INT NOT NULL,
  `descrição` VARCHAR(45) NULL,
  `valor mão de obra` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idServiço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peça`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peça` (
  `idPeça` INT NOT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Valor Unitário` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idPeça`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço_has_Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço_has_Serviço` (
  `Ordem de Serviço_idOrdem de Serviço` INT NOT NULL,
  `Serviço_idServiço` INT NOT NULL,
  `Valor- Praticado` DECIMAL(10,2) NULL,
  PRIMARY KEY (`Ordem de Serviço_idOrdem de Serviço`, `Serviço_idServiço`),
  INDEX `fk_Ordem de Serviço_has_Serviço_Serviço1_idx` (`Serviço_idServiço` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_has_Serviço_Ordem de Serviço1_idx` (`Ordem de Serviço_idOrdem de Serviço` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_has_Serviço_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_idOrdem de Serviço`)
    REFERENCES `mydb`.`Ordem de Serviço` (`idOrdem de Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_has_Serviço_Serviço1`
    FOREIGN KEY (`Serviço_idServiço`)
    REFERENCES `mydb`.`Serviço` (`idServiço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço_has_Peça`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço_has_Peça` (
  `Ordem de Serviço_idOrdem de Serviço` INT NOT NULL,
  `Peça_idPeça` INT NOT NULL,
  `Quantidade` INT NULL,
  `Venda-Valor` DECIMAL(10,2) NULL,
  PRIMARY KEY (`Ordem de Serviço_idOrdem de Serviço`, `Peça_idPeça`),
  INDEX `fk_Ordem de Serviço_has_Peça_Peça1_idx` (`Peça_idPeça` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_has_Peça_Ordem de Serviço1_idx` (`Ordem de Serviço_idOrdem de Serviço` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_has_Peça_Ordem de Serviço1`
    FOREIGN KEY (`Ordem de Serviço_idOrdem de Serviço`)
    REFERENCES `mydb`.`Ordem de Serviço` (`idOrdem de Serviço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_has_Peça_Peça1`
    FOREIGN KEY (`Peça_idPeça`)
    REFERENCES `mydb`.`Peça` (`idPeça`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
